<a href="https://colab.research.google.com/github/SanjanaPurohit2000/116_SanjanaPurohit/blob/master/Lab1/Lab1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd

matrix3x2 = np.array([[4, 7], [3, 2], [1, 3]])
matrix2x3 = np.array([[1, 5, 2], [9, 7, 5]])

print('3 x 2 matrix : \n', matrix3x2)
print('\n 2 x 3 matrix : \n', matrix2x3)

3 x 2 matrix : 
 [[4 7]
 [3 2]
 [1 3]]

 2 x 3 matrix : 
 [[1 5 2]
 [9 7 5]]


In [ ]:
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.21979884 0.80544938 0.89906897 0.62568857]
 [0.6358077  0.39879675 0.86892448 0.68851151]
 [0.15337211 0.89202264 0.39906997 0.74482112]]


In [ ]:
# matrix multiplication
matmul = np.dot(matrix3x2, matrix2x3)
print(matmul)

[[67 69 43]
 [21 29 16]
 [28 26 17]]


In [ ]:
# elemet wise matrix multiplication
result = [[0 for x in range(len(matrix3x2))] for y in range(len(matrix2x3[0]))]

for i in range(len(matrix3x2)): 
  for j in range(len(matrix2x3[0])): 
    for k in range(len(matrix2x3)): 
      result[i][j] += matrix3x2[i][k] * matrix2x3[k][j]
 
print('Element wise multiplication : \n', result)

Element wise multiplication : 
 [[67, 69, 43], [21, 29, 16], [28, 26, 17]]


In [ ]:
mean = np.mean(matrix3x2)
print(mean)

3.3333333333333335


6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data=pd.read_csv('/content/drive/My Drive/ML/mtcars.csv')

In [ ]:
del data['model']

meancenter = data.apply(lambda e: e - e.mean())
print(meancenter.head())


        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
