<a href="https://colab.research.google.com/github/SanjanaPurohit2000/116_SanjanaPurohit/blob/master/Lab5/116_Lab5_Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.


And now using two different targets: Apples and Oranges

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [ ]:
# Imports
import torch.nn as nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print("Inputs : \n",inputs)
print("Targets : \n",targets)

Inputs : 
 tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
Targets : 
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

Dataset and DataLoader

We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [ ]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [ ]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [ ]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]])
tensor([[103., 119.],
        [103., 119.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 22.,  37.]])


In [ ]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[-0.1615,  0.2295, -0.4187],
        [ 0.5356, -0.0982, -0.5332]], requires_grad=True)
Parameter containing:
tensor([0.0344, 0.0922], requires_grad=True)



nn.Linear

Instead of initializing the weights & biases manually, we can define the model using nn.Linear.

In [ ]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.1615,  0.2295, -0.4187],
         [ 0.5356, -0.0982, -0.5332]], requires_grad=True),
 Parameter containing:
 tensor([0.0344, 0.0922], requires_grad=True)]

In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-14.3831,   9.6800],
        [-21.2636,   6.0602],
        [ -7.5485,   2.5991],
        [-22.0619,  30.7683],
        [-18.3872,  -9.7076],
        [-14.3831,   9.6800],
        [-21.2636,   6.0602],
        [ -7.5485,   2.5991],
        [-22.0619,  30.7683],
        [-18.3872,  -9.7076],
        [-14.3831,   9.6800],
        [-21.2636,   6.0602],
        [ -7.5485,   2.5991],
        [-22.0619,  30.7683],
        [-18.3872,  -9.7076]], grad_fn=<AddmmBackward>)

In [ ]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
# Import nn.functional
import torch.nn.functional as F


Loss Function

Instead of defining a loss function manually, we can use the built-in loss function mse_loss.

In [ ]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
#loss = loss_fn(? , ?)
#print(loss)

In [ ]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)


Optimizer

Instead of manually manipulating the weights & biases using gradients, we can use the optimizer optim.SGD.

In [ ]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
   for epoch in range(num_epochs):
       for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
   print('Training loss: ', loss_fn(model(inputs), targets))


Train the model

We are ready to train the model now. We can define a utility function fit which trains the model for a given number of epochs.

In [ ]:
# Train the model for 100 epochs
fit(100 , model , loss_fn, opt)

Training loss:  tensor(70.2975, grad_fn=<MseLossBackward>)


In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.5071,  72.6277],
        [ 78.5817,  95.8856],
        [125.1359, 140.4850],
        [ 28.1066,  49.4670],
        [ 91.4957, 103.5391],
        [ 58.5071,  72.6277],
        [ 78.5817,  95.8856],
        [125.1359, 140.4850],
        [ 28.1066,  49.4670],
        [ 91.4957, 103.5391],
        [ 58.5071,  72.6277],
        [ 78.5817,  95.8856],
        [125.1359, 140.4850],
        [ 28.1066,  49.4670],
        [ 91.4957, 103.5391]], grad_fn=<AddmmBackward>)

In [ ]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])