<a href="https://colab.research.google.com/github/SanjanaPurohit2000/116_SanjanaPurohit/blob/master/Lab3/116_Lab3_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1 :- Try the algo on Dataset3 - OneHotEncoding of features : and train test division 85% - 15%.



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#import libraries

import numpy as np 
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
#prepare dataset

dataset = pd.read_csv('/content/drive/My Drive/ML/L3/Dataset3.csv')
print("Data :- \n",dataset)
print("Data Statistics :- \n",dataset.describe())

Data :- 
    Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0
Data Statistics :- 
         Humidity      Class
count  14.000000  14.000000
mean    1.000000   0.571429
std     0.679366   0.513553
min     0.000000   0.000000
25%     1.000000   0.000000
50%     1.000000   1.000000
75%     1.000000   1.000000
max     2.000000   1.000000


In [ ]:
col_list = ["Outlook", "Temp", "Wind", "Humidity", "Class"]
df = pd.read_csv("/content/drive/My Drive/ML/L3/Dataset3.csv", usecols=col_list)

outlook = df["Outlook"]
print(outlook)
temp = df["Temp"]
print(temp)
wind = df["Wind"]
print(wind)
humidity = df["Humidity"]
print(humidity)
play = df["Class"]
print(play)

0     R
1     R
2     O
3     R
4     S
5     O
6     O
7     R
8     O
9     S
10    R
11    O
12    O
13    S
Name: Outlook, dtype: object
0     H
1     H
2     H
3     M
4     C
5     C
6     C
7     M
8     C
9     M
10    C
11    M
12    H
13    M
Name: Temp, dtype: object
0     F
1     T
2     F
3     F
4     F
5     T
6     T
7     F
8     F
9     F
10    T
11    T
12    F
13    T
Name: Wind, dtype: object
0     1
1     2
2     1
3     1
4     1
5     0
6     1
7     1
8     0
9     2
10    2
11    0
12    1
13    1
Name: Humidity, dtype: int64
0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    0
11    1
12    1
13    0
Name: Class, dtype: int64


In [ ]:
#Digitize the data set using encoding

from sklearn.preprocessing import OneHotEncoder

X = tuple(zip(outlook, temp, humidity, wind))
print(X)

X_enc = OneHotEncoder().fit_transform(X).toarray()
print("\n",X_enc)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y_enc = le.fit_transform(play)
print("\n",Y_enc)


(('R', 'H', 1, 'F'), ('R', 'H', 2, 'T'), ('O', 'H', 1, 'F'), ('R', 'M', 1, 'F'), ('S', 'C', 1, 'F'), ('O', 'C', 0, 'T'), ('O', 'C', 1, 'T'), ('R', 'M', 1, 'F'), ('O', 'C', 0, 'F'), ('S', 'M', 2, 'F'), ('R', 'C', 2, 'T'), ('O', 'M', 0, 'T'), ('O', 'H', 1, 'F'), ('S', 'M', 1, 'T'))

 [[0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]]

 [0 0 1 1 1 0 1 0 1 1 0 1 1 0]


In [ ]:
#merge different features to prepare dataset

print("\nFeatures\n")
for pair in X_enc:
  print(pair)


Features

[0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
[0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1.]
[1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
[0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
[0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
[1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1.]
[1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1.]
[0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
[1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
[0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]
[0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
[1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
[1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
[0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_enc, Y_enc, test_size = 0.15, random_state = 116)
print(x_train)

[[0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1.]]


In [ ]:
#Create and train NBClassifier

model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
#Predict New Output Data

y_predicted = model.predict(x_test)
print(x_test)
print('\n', y_predicted)

[[0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0.]]

 [1 1 1]


In [ ]:
#Model Perfomance

from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print('Accuracy is :- ',metrics.accuracy_score(y_test, y_predicted))

#precision and recall
precision = precision_score(y_test, y_predicted)
recall = recall_score(y_test, y_predicted)
print('Precision :- ', precision)
print('Recall :- ',recall)

Accuracy is :-  0.3333333333333333
Precision :-  0.3333333333333333
Recall :-  1.0


In [ ]:
#Question For Task1

#(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

#Outlook(O, R, S) = Rainy, Temp(C, H, M) = Mild, Humidity(high, low, normal) = Normal, Wind(F, T) = False
output = model.predict([[0,1,0, 0,0,1, 0,0,1, 1,0]])
print('Prediction  :-   ', output)

#(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?

#Outlook(O, R, S) = Sunny, Temp(C, H, M) = Cool, Humidity(high, low, normal) = High, Wind(F, T) = True
output = model.predict([[0,0,1, 1,0,0, 1,0,0, 0,1]])
print('Prediction  :-  ', output)

Prediction  :-    [0]
Prediction  :-   [1]


In [ ]:
#Create And Train Gaussian NB Clssifier
gnb = GaussianNB()

gnb.fit(x_train, y_train)   #train the model using training sets

target_prediction = gnb.predict(x_test)  #predict the response of test dataset